#!/usr/bin/env ansible-playbook

- name: Setup Pi for art installation hardware used in Life In Lights
  hosts: installations
  tasks:
    - name: Install Leiningen script
      copy: src=files/lein dest=/usr/local/bin/lein mode=0755
      sudo: yes

    - name: Install LIRC package
      apt: name=lirc update_cache=yes
      sudo: yes
    - name: Install custom /etc/lirc/hardware.conf (Enable LIRC)
      copy: src=files/hardware.conf dest=/etc/lirc/hardware.conf mode=0644
      sudo: yes
    - name: Install custom /etc/modules (Enable dev and gpio)
      copy: src=files/modules dest=/etc/modules mode=0644
      sudo: yes
    - name: Install custom /etc/lirc/lircd.conf (Define remote codes)
      copy: src=files/lircd.conf dest=/etc/lirc/lircd.conf mode=0644
      sudo: yes
    - name: Install custom /home/pi/lircd.conf (Define remote codes)
      copy: src=files/lircd.conf dest=/home/pi/lircd.conf
      sudo: yes
    - name: Restart LIRC service
      service: name=lirc state=restarted
      sudo: yes
      
    - name: Install unclutter package
      apt: name=unclutter
      sudo: yes
      
    - name: Install custom boot configurations (LIRC GPIO, Splash, Camera LED)
      copy: src=files/config.txt dest=/boot/config.txt mode=0644
      sudo: yes
      
    - name: Install custom autostart (Mouse and Screensaver settings)
      copy: src=files/autostart dest=/etc/xdg/lxsession/LXDE/autostart mode=0644
      sudo: yes
      
    - name: Install custom lightdm.conf (Screen blanking settings)
      copy: src=files/lightdm.conf dest=/etc/lightdm/lightdm.conf mode=0644
      sudo: yes      

    - name: Set timezone
      command: /usr/bin/timedatectl set-timezone EST5EDT
      sudo: yes

    - name: Install custom wallpapers
      copy: src=files/wallpapers dest=/home/pi

    - name: Set custom wallpaper
      lineinfile: dest=/home/pi/.config/pcmanfm/LXDE-pi/desktop-items-0.conf  regexp=^wallpaper= line=wallpaper=/home/pi/wallpapers/lifeinlights-wallpaper-1280-720.png

    - name: Check out sketch repository
      git: repo=https://github.com/LifeInLights/twyla-opus.git dest=/home/pi/twyla-opus

    - include: setup_cron_schedule.yml
