#!/usr/bin/env ansible-playbook

- name: Install Twyla-Opus repository
  hosts: installations	
  tasks:
    - name: Checkout/Update Twyla-Opus repository
      git: repo=https://github.com/LifeInLights/twyla-opus.git dest=/home/pi/twyla-opus
      
