#!/usr/bin/env ansible-playbook

#https://support.ansible.com/hc/en-us/articles/201958037-Reboot-a-server-and-wait-for-it-to-come-back
- name: Reboot Pis
  hosts: lifeinlights
  tasks:
    - name: restart machine
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      sudo: true
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for server to come back
      local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=30 timeout=300
      sudo: false
