#!/usr/bin/env ansible-playbook

- name: Setup Pi scheduling for art installation hardware used in Life In Lights
  hosts: installations
  tasks:
    - cron: name="Update twyla-opus" minute="50" hour="16" job="cd /home/pi/twyla-opus && git pull"
    - cron: name="Turn on projector" minute="0,10,20,30,40,50" hour="*" job="irsend SEND_ONCE /home/pi/lircd.conf KEY_POWER"
    - cron: name="Start presentation" minute="1,11,21,31,41,51" hour="*" job="cd /home/pi/twyla-opus/spectacles && export DISPLAY=:0 && /usr/local/bin/lein run -m spectacles.presenter >> /home/pi/presentation.log 2>&1"
    - cron: name="Shut off projector" minute="8,18,28,38,48,58" hour="*" job="irsend SEND_ONCE /home/pi/lircd.conf KEY_POWER && sleep 3 && irsend SEND_ONCE /home/pi/lircd.conf KEY_POWER"
    - cron: name="Shut off presentation" minute="9,19,29,39,49,59" hour="*" job='pkill -f "java.*lein"'
